# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: velvet_central_dongle dongle_display_view_pro_micro
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: velvet_central_dongle  
  - board: nice_nano_v2
    shield: velvet_peripheral_left
    artifact-name: velvet_peripheral_left
  - board: nice_nano_v2
    shield: velvet_peripheral_right
    artifact-name: velvet_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
